### PR TITLE
Allow Changing `Context` in `newListr()`

### PR DESCRIPTION
**Pull request by BeeeQueue**
Will allow something like this:

```ts
type Context = { foo: string }
type Extra = { bar: string }

const tasks = new Listr<Context>([
  { task: () => {} },
  {
    task: (ctx, task) => {
      task.newListr<Context & Extra>([/* tasks */], {
        ctx: {...ctx, bar: "bar" }
      })
    },
  },
], {
  ctx: { foo: "foo" }
})
```

### CODE REVIEW

**Comment by cenk1cenk2** [comment]
Hey @BeeeQueue ,
Thank you for your contribution and your time on this. I will fix the CI action and merge it tomorrow hopefully.

**Comment by BeeeQueue** [comment]
It seems like this still does not work because of this: https://github.com/listr2/listr2/blob/962ec3de8b2cf5e5987c251d5ec87a4494100d0c/src/listr.ts#L116

The second context is passed in as `this.options?.ctx` while the first one is sent in as `context`, always overriding it.

image

I propose changing it so the parameter overrides any properties in the options, to make the options act as default values

```ts
this.ctx = {
  ...this.options?.ctx ?? {},
  ...context
}
```

It would _technically_ be a breaking change, but the old behavior is very strange so I wouldn't put a _lot_ of money on people relying on it...

**Comment by cenk1cenk2** [comment]
This should not be a problem, we can put the past in context first, I would not consider this as a breaking change.

**Comment by cenk1cenk2** [comment]
This will have an obvious downfall that I have initially missed since context manipulation relies on object mutability.

If we pass a different context to the subtask, the values inside that context will not propagate to the main one. It will just use that context inside the `newListr` itself and when the subtask is finished it will just scrap that context completely.

Is this the use-case you are aiming for, having a different context that only makes sense inside the subtask itself and you will not use that in the main task?

**Comment by cenk1cenk2** [comment]
You can check the behavior I am talking of in the test I have added.

**Comment by BeeeQueue** [comment]
I did not realise that would happen, but that in my eyes looks like good behavior? The inner listr instance should not leak its own context to its parents

If you want to set a value on the parent's contexts you always have them available from their task functions:

```ts
const tasks = new Listr([
  { task: (rootCtx, rootTask) => 
    rootTask.newListr({ task: (ctx, task) => {
      rootCtx.something = "else"
    }})
  }
])
```

**Comment by cenk1cenk2** [comment]
Yes exactly, I will merge this in! Thank you for your work on this.

**Comment by cenk1cenk2** [comment]
This still should be added to the documentation, I will leave a note for myself here.

**Pull request merged**
