### PR TITLE
Rework Build System, Drop Node 10, Simplify Configs

### PR DESCRIPTION
**Pull request by BeeeQueue**
I've been using this to work on the PRs I've made, dogfooding it in the project that I'm making that uses listr2.
Seems to work as before, but I have no idea if the CI will pass 😅 

I also changed the event triggering PR CI builds to `pull_request`, as `pull_request_target` is [meant for when you want to run things based on the event triggering it, not the things in the PR](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target). This will also fix the errors in #615 

I tried to remove `ts-node` too, by simplifying the jest setup to make the tests runnable with just `jest`, but ran into issues with the `rewire` shortcut paths not being updated without `ts-node` running it...

- Replaces complex system with `tsc`, `tsc-watch`, `tsconfig-replace-paths` (which doesn't even work on windows!) with `tsup`.
  _This will change the output from being separate files to being one bundled file_
- Drops supported non-LTS versions of node (10)
- Adds ESM build
- Simplify (shorten, use presets in) jest, TS configs
  - Enabled `allowSyntheticDefaultImports` as it was required for `tsup` to build, and it's nicer to work with IMO 😄

### CODE REVIEW

**Comment by BeeeQueue** [comment]
No idea what's happening here, the CI seems to be running against master instead of my branch??

**Comment by BeeeQueue** [comment]
Ah, it's because of `pull_request_target`... Updated the body of the PR

**Comment by cenk1cenk2** [comment]
Thank you again @BeeeQueue,

I am very grateful for this pull request since this was something that I should have done long ago. The only problem that I can see is the ESM-only dependencies. I guess it is not bundling the dependencies right? Since we still have a common-js version, updating those would be out of the question still. I was postponing ESM conversion till I had ditched `rxjs` and `log-update` dependencies to make it into breaking change bundle, which I have failed miserably in my last tries, but I guess we can go ahead with the error collection and make this a breaking change.

I am not sure to drop the common-js version or not since I rely on them in some legacy dependencies for work, so this would be a good compromise still.

Thank you again sincerely for your time on this. Again I will merge this in tomorrow hopefully if it is not a problem.

**Comment by BeeeQueue** [comment]
> The only problem that I can see is the ESM-only dependencies. I guess it is not bundling the dependencies right?

Indeed, it does not bundle anything in `dependencies` or `peerDependencies`.

Even if it did, it still converts all bundled code to work with the module system it builds for so that'd still work 🙂

**Comment by cenk1cenk2** [comment]
Hey @BeeeQueue,

Again sincerly thank you for your work on this. I merged it all to the temporary branch of develop but it has one big problem with ts-up which is ignoring extends field in tsconfig file. I might have to wait until the issue is closed.

https://github.com/egoist/tsup/issues/524

**Comment by BeeeQueue** [comment]
Huh i haven't experienced that myself... Maybe it's because of something in the tsconfig cuasing it to use a different compiler? In the issue he mentions decorators which I've never used in a project with tsup

**Comment by cenk1cenk2** [comment]
It should not be much of a problem, we can just do until this  issue is fixed ofc, a direct tsconfig file with every option included.

**Pull request merged**
