### PR TITLE
Add Option to Disable Error Collection

### LINKED ISSUE #600: Version 3.13.2 and later results in application crash and memory leaks
Reproducible repository here: https://github.com/Baune8D/listr2-clone-failure

`v3.13.5` memory usage spins out of control and the application crashes as more and more tasks fail.
`v3.13.2` no issues with memory usage, but the application gets completely unresponsive as more and more tasks fails.
`v3.13.1` works as it should, no problems here at all.

I guess this is related to cloning introduced in v3.13.2

Included in the example repository is 3 npm scripts:
* `npm run memoryleak` triggers the memory leak issue with version 3.13.5
* `npm run crashes` triggers application crash with version 3.13.2
* `npm run works` runs without problems with version 3.13.1

This has only been tested on `Windows 11` using `Windows Terminal` and `Node.js 16.13.0`

### PR DESCRIPTION
**Pull request by BeeeQueue**
I ran into the same(?) issue as #600 and found that commenting out https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts#L58 fixed it based on the comments in the issue.

Closes #600(?)

### CODE REVIEW

**Comment by cenk1cenk2** [comment]
Thank you @BeeeQueue for this merge request, I would only change to enable this by default and merge it with your other request as a breaking change. I doubt that many people including me use this feature since it was rather fixed recently and causing more problems than it solves. Maybe we can just collect the `error.message` when `collectErrors` is set to false, so we do know something has gone wrong.

I will merge this is hopefully tomorrow.

**Comment by BeeeQueue** [comment]
Maybe a better solution would be to have the setting be something like `errorCollection: "full" | "minimal" | false"`?

Then it can do the full copy on `"full"`, just save `Error.{message,stack}` on `"minimal"`, and nothing when false

**Comment by cenk1cenk2** [comment]
Yeah that would be even better. What should the default will be I guess minimal without copying the context for each error it would be very hard to have a memory leak.

**Comment by BeeeQueue** [comment]
Looking at the function again it would be better to just save the error and save the extra info (ctx, task) if it's not `"minimal"`.

Then the question becomes how do we know which step actually errored? With no task or context in the error it becomes quite hard to tell in a big list of tasks.

I added something called `currentPath` to `Task`, which is all the task's parent's titles, which we can then use to show which task crashed.

**Pull request merged**
