### PR TITLE
Replace Chalk with Colorette

### PR DESCRIPTION
**Pull request by NickKaramoff**
One of the dependencies that `listr2` uses is Chalk. While being an excellent tool, it's unnecessarily bulky. Upon installation, Chalk adds another 5 dependencies, taking 200 KB of space — and all that for some ANSI tags.

This pull request replaces Chalk with Colorette. [Colorette](https://github.com/jorgebucaran/colorette) is:

* **Small**: it has no dependencies and takes 5 times less space, than Chalk:  
  Picture showing size difference between Chalk and Colorette installations: 200K vs. 36K
* **Fast**: it's 50% faster than Chalk:  
  Picture showing speed difference between Chalk and Colorette: 410K vs. 627K ops/sec
* **Simple**: Colorette's API is very similar to those of Chalk
* **Widely used**: [Autoprefixer](https://github.com/postcss/autoprefixer/blob/88892154c9215e92fee011ff91c10d4b4ba5f1f6/package.json#L34), [PostCSS](https://github.com/postcss/postcss/blob/3b86dcbb2198b885a3e76a90a99959866da67a0e/package.json#L67) and [Webpack](https://github.com/webpack/webpack-cli/blob/2b8812a3b847b62195079232d42245998be7d419/package.json#L60) use Colorette instead of Chalk

Moving to Colorette reduces `listr2`'s dependency footprint and increases performance.

----

**Caveat:** since the colour "orange" is not a standard terminal colour, calls to it have been replaced with "yellow".

### CODE REVIEW

**Comment by NickKaramoff** [comment]
For some reason, lint fails on Node 15 (and, for that matter, 16). This appears to be some internal error of either ESLint or Typescript (or the plugin, connecting both)

<details>
<summary>Details</summary>

```
$ eslint --ext .ts,.js,.tsx,.jsx src/

Oops! Something went wrong! :(

ESLint: 7.26.0

TypeError: Cannot read property 'type' of null
Occurred while linting /home/runner/work/listr2/listr2/src/interfaces/task.interface.ts:2
    at isExportNameClass (/home/runner/work/listr2/listr2/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:51:69)
    at checkForNewLine (/home/runner/work/listr2/listr2/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:79:45)
    at checkImport (/home/runner/work/listr2/listr2/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:133:9)
    at /home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/listr2/listr2/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
error Command failed with exit code 2.
info Visit yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.
```

</details>

**Comment by cenk1cenk2** [comment]
Thank you @NickKaramoff . This is a great improvement. Yeah it currently has some problems with linting and such, I am really busy with other projects therefore did not had the chance to improve up on this library. But will merge it anyway.

**Comment by cenk1cenk2** [comment]
I would also like to reduce dependencies, especially rxjs for a event emitter approach but have not yet made it work. Hopefully in the upcoming months I will release it with v4.

**Pull request merged**
