### PR TITLE
Add ability for showing duration of tasks

### PR DESCRIPTION
**Pull request by AJHenry**
This adds the behavior of adding the ability to time tasks as defined [here](https://github.com/SamVerschueren/listr-update-renderer/pull/24) and adds it to the default renderer

It adds the flag `showTimer` to the renderer options and then displays a timer next to the title in form `title [00:00]`

I won't have much time to refactor this in the upcoming days, so I will leave this up to you to do with what you want

### CODE REVIEW

**Comment by cenk1cenk2** [comment]
This could be a great addition. But I would prefer to make this flag available on task basis for the default renderer. Because some unrelated tasks can take less then one second. What do you think about it?

**Comment by AJHenry** [comment]
Either way makes sense to me, timing a set of tasks as well as individual tasks seems useful

**Comment by jimbuck** [comment]
Hey there! I'm the author of the PR for this feature for listr-update-renderer. I actually originally had it configurable at the top level and per task, but removed the per-task option to simplify the PR. It was really nice, so I'm glad you're implementing it in your rewrite!

**Comment by cenk1cenk2** [comment]
It will be a great addition. I always did the timing manually. Hopefully I will get to it in the weekend.

**Comment by AJHenry** [comment]
@jimbuck Thanks for doing most of the heavy lifting! Looks like we can add an option for both the renderer and the task options. If @cenk1cenk2 can't get to it this weekend, I can tackle it next week

**Comment by cenk1cenk2** [comment]
I have implemented this in hope you like it. I did not merge it directly so I will close this, but it is almost the same idea. It both has flags for per subtask and per task option for `showTimer` which the prior will overwrite the latter option. It will only log minutes and seconds, and if it is less than a second it will log it like `0.xs`.

In the meantime, I also isolated message channels of `error` and `skip` messages, because I realized that with your prior issue #137 logging them as output messages.

**Pull request closed without merging**
